### ISSUE TITLE
Can I ask a silly question? I'm a new modder

### ISSUE THREAD

**Issue by serephus** [aers/SprintJumpSSE#1]
I want to know how did u get these result in IDA, as far as I tried, I only got a bunch of 'db' 'dq' in these address, so i'm wondering how did u get these right.

IDA made a lot of these mistakes, how can i fix these mistakes ? Do I need to fix these manually one by one or ... ?

Thx.

/*
sprint check code in jump handler, 1.5.39:
.text:000000014070962C loc_14070962C:                          ; CODE XREF: sub_140709550+CA↑j
.text:000000014070962C                 mov     rcx, cs:qword_142F4DEF8
.text:0000000140709633                 call    sub_140608CB0
.text:0000000140709638                 test    al, al
.text:000000014070963A                 jnz     short loc_140709669
.text:000000014070963C                 mov     rcx, cs:qword_142F4DEF8
.text:0000000140709643                 mov     edx, 100h
.text:0000000140709648                 add     rcx, 0B8h
.text:000000014070964F                 call    sub_14063C7E0
.text:0000000140709654                 test    al, al
.text:0000000140709656                 jnz     short loc_140709669
.text:0000000140709658                 mov     rcx, cs:qword_142F4DEF8
.text:000000014070965F                 add     rsp, 20h
.text:0000000140709663                 pop     rbx
.text:0000000140709664                 jmp     sub_1405D2430
jumping to 709658 bypasses check
*/

**Comment by aers** [comment]
Skyrim is a Steam game so the exe is protected with steamstub and decrypted at runtime. Use https://github.com/atom0s/Steamless on it before opening it in IDA.

**Comment by serephus** [comment]
Thx
